### ISSUE TITLE
Suggestions to rename top-level folders to make them easier to understand for "outsiders"

### ISSUE THREAD

**Issue by AKuederle** [mobilise-d/mobgap#134]
At the moment we use shorthands for most algorithms (GSD, SL, ...). While these might be easy to be understood within the Mobilise-D consortium, they might be confusing.

I would suggest to at least change the top-level folders of the these algorithm groups to better to understand names.

Suggestions:

gsd -> gait_sequences
cad -> cadence
icd -> inital_contacts
td -> turning
lrc -> laterality/left_right? <- Not sure about that one yet
wba -> maybe group under the aggregation folder?

Note, that I suggest skipping the implied "detection" in the names as well. I think this should be clear and helps to keep the names somewhat short.

The algorithms itself still carry the abbreviation in the name. I think this is a good approach and we should keep it.

**Comment by pltsc18** [comment]
I totally agree, I also like "laterality" for `lrc` :)

**Comment by alexstihi** [comment]
I agree, this new naming convention is much more clearer to external users. For L/R detection, how about `contact_side`?

**Comment by DMegaritis** [comment]
Fully agree as well! 
For lrc I would suggest "left_right" since "laterality" implies the choice of using one side of body by humans.
