### ISSUE TITLE
Missing reference data for HA-002

### ISSUE THREAD

**Issue by pltsc18** [mobilise-d/mobgap#139]
It looks like reference data from both INDIP and Stereophoto are missing from subject HA-002 of the example data. 

Example files that compare the outputs of the algorithms to the INDIP or stereophoto reference work well with all the trials of subject HA-001 and MS-001, except if you process subjects HA-002. However, trying to access reference data of subject HA-002 results in an exception: 
`(<class 'KeyError'>, "None of ['wb_id'] are in the columns", <traceback object at 0x000001BDC0D3D2C0>)`

**Comment by AKuederle** [comment]
When I run it in the current version, I don't get an error, but an empty dataframe.

It seems like there is not enough gait to define a WB (as you figured out). Given that this does not seem to error any more in the current version, I will close this issue
