### ISSUE TITLE
Add example for evaluation DMOs that are already aggregated (e.g., per day)

### ISSUE THREAD

**Issue by a-mosquito** [mobilise-d/mobgap#152]
**Please consider also using the Discussion tab for general questions or ideas, in particular if they are not linked to the development, but rather scientific questions/discussions.**

**Describe the issue**
A clear and concise description of what the issue is.

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by a-mosquito** [comment]
change naming from gait sequences to WB in text and variables, explain how both evaluation approaches from WBA paper would be implemented

**Comment by AKuederle** [comment]
I already adapted the naming and some of the structure. What is missing, is the part of the example that shows the "aggregate then error" approach. For this we should probably move the detailed explanations on how the error calculation works up into the new part (or have a completely seperate section that explain the details?). Whatever you think is best to keep everything readable
