### ISSUE TITLE
Definition of error metrics?

### ISSUE THREAD

**Issue by richrobe** [mobilise-d/mobgap#177]
In `mobgap`, error metrics are defined as `predicted - true`, whereas elsewhere (e.g., in scikit-learn, https://scikit-learn.org/stable/modules/model_evaluation.html#regression-metrics) they are defined as `true - predicted`

**Comment by AKuederle** [comment]
After some further research, it seems in coherent how these errors are defined in literature. To aid interpretation (overestimation -> positive error, underestimation -> negative error) and be coherent with past Mobilise-D paper, we will stick to the current definition.
