### ISSUE TITLE
[ALGO] {TD_ElGohary}

### ISSUE THREAD

**Issue by CJkirk105** [mobilise-d/mobgap#31]
This issue is meant to track the implementation of the {TD_ElGohary}

**Short description**: The turning detection toolbox contains code (MATLAB, R2018b) for detection of turning using angular accelerations recording with triaxial gyroscope worn/fixed on the lower back (close to body centre of mass)

 project contains the code of the turning detection algorithm decribed in El-Gohary et al.  2014.

Four output files will be stored in the `outdir` in `.json` and `.mat` format, respectively, and both with an algorithm generic and algorithm specific file name. The `Turning_ElGohary` algorithm provides as output the regions of turnings with start and end in seconds since the start of the recording / trial, and several related parameters like the turning angle or the peak angular velocity.

**Reference papers**
El-Gohary, M., Pearson, S., McNames, J., Mancini, M., Horak, F., Mellone, S., & Chiari, L. (2014). Continuous monitoring of turning in patients with movement disability. Sensors (Basel, Switzerland), 14(1), 356–369. https://doi.org/10.3390/s140100356

**Comment by AKuederle** [comment]
Correct PR is not #131

**Comment by AKuederle** [comment]
Close as #131 merged
