### ISSUE TITLE
Add support for unilaterally worn sensors (e.g., wrist)

### ISSUE THREAD

**Issue by felixkluge** [mobilise-d/mobgap#42]
For the wrist sensor (INDIP system), 'LeftWrist' or 'RightWrist' is stored as position in the data.mat file depending on the handedness of the participant. 

It would be favourable to be able to load the dataset as follows by generically indicating 'Wrist':
```
mobilised_dataset = GenericMobilisedDataset(paths_list = paths, 
                                            raw_data_sensor = 'INDIP',
                                            sensor_positions = ('Wrist',),
                                            test_level_names = ("timemeasure", "recording")
                                            )
```

**Comment by muschellij2** [comment]
Are wrist-worn devices supported? I know the methods were trained on lower back and may be generalizable, but the docs explicitly seem to indicate this is a "stupid" idea:
> 4. The library should not prevent users from "intentional stupidity".
   For example, if users decide to apply an event detection method designed to only run on data from sensors attached to 
   the lower-back on data from a wrist-worn sensor, **let them**.

https://github.com/mobilise-d/mobgap/blob/c9235faa7e67fb52a4ea89e3bd310be09e2d6168/docs/guides/project_structure.md?plain=1#L45

**Comment by AKuederle** [comment]
The issue here was about loading data from wrist worn devices not applying the provided algorithms. At the moment non of the included algorithms are explicitly tested or recommended to be used on wrist devices. But @felixkluge has done some work in this direction:

https://pubmed.ncbi.nlm.nih.gov/38691395/
