### ISSUE TITLE
Refactor evaluation examples

### ISSUE THREAD

**Issue by AKuederle** [mobilise-d/mobgap#96]
At the moment we add a small sectio about algo evaluation at the end of every algo example. This is great to directly get some information about how the algo performs on some limited piece of data.

However, this leads to duplicated explanations for some of the details of how the evaluation works.

We should refactor this, so that there is one example that shows the details on how the evaluation works and the examples from all the other algorithms only contain the relevant code and reference the other example for more details.

Likely the cleanest verison would be to have a completly separate example for evaluation in each of the algo example folders, that skips over basically all details of applying the algorithm, but spends some time explaining what you might want to compare/how to do it/ what options there are.

**Comment by a-mosquito** [comment]
Done in the scope of #86 and #107
